Bitfit
bigscience-workshop/multilingual-modeling pull request #22
Opened 2022-06-25 09:13 UTC by lintangsutawika

2022-07-01 16:17 UTC, lintangsutawika commented
In `madx_run_clm.py` I added a new arg `finetuning_strategies` that can be extended to choose any other parameter-efficient finetuning methods.

2022-07-01 16:42 UTC, yongzx commented
I will review this! Thanks!

> In madx_run_clm.py I added a new arg finetuning_strategies that can be extended to choose any other parameter-efficient finetuning methods.

It's already in there: `lang_adapt_strategies`.

2022-07-01 16:54 UTC, yongzx requested changes

2022-07-01 16:54 UTC, yongzx commented on scripts/lang_adapt/bitfit/train_tokenizer_update.sh
> +python tokenized4clm_sampled.py --lang $lng --model $model --tokenizer_dir $tokenizer_dir --vocab_size $vocab_size --sample_size $sample_size --extend_vocab
Is it just the batch script for training tokenizer?

2022-07-01 16:55 UTC, yongzx commented on scripts/lang_adapt/madx_run_clm.py
> +    finetuning_strategies: str = field(
Also, do add "bitfit" to `assert model_args.lang_adapt_strategies in ('emb', 'emb-and-adpt', 'emb-then-adpt', 'lora')` (in the latest master branch)

2022-07-01 16:56 UTC, yongzx commented
@lintangsutawika Left some reviews. Everything else LGTM.

2022-07-02 06:21 UTC, lintangsutawika commented
@yongzx Bitfit isn't really an adapter, it just freezes the biases of a given model. I'm not sure it fits in the `modify_model`.

I've placed it it line 625 currently. 
```
        elif model_args.lang_adapt_strategies == "bitfit":
            for name, param in model.transformer.named_parameters():
                if 'bias' not in name:
                    param.requires_grad = False
```

2022-07-04 14:13 UTC, yongzx commented
Thanks Lintang! I will run it today and merge it by EOD.

2022-07-05 17:28 UTC, merged